name: horizontal_picker
version: 1.2.0
description: You can select your value on Horizontal Picker while scrolling on items.
homepage: https://github.com/leventkantaroglu/
repository: https://github.com/leventkantaroglu/horizontal_picker
documentation: https://github.com/leventkantaroglu/horizontal_picker/blob/master/README.md

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
 
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
